// ⚡ PERFORMANCE: Static confidence scale outside reactive system
const CONFIDENCE_SCALE = [
    { value: 1, label: "1", description: "Not confident", color: "bg-red-500" },
    { value: 2, label: "2", description: "Low confidence", color: "bg-orange-500" },
    { value: 3, label: "3", description: "Moderate confidence", color: "bg-yellow-500" },
    { value: 4, label: "4", description: "Good confidence", color: "bg-blue-500" },
    { value: 5, label: "5", description: "Very confident", color: "bg-green-500" }
];

export function createState() {
    return {
        darkMode: false,
        selectedPaper: 'All Topics',
        activeSection: 'measurements_errors',
        sidebarVisible: true,
        expandedGroups: {},
        viewMode: 'spec',
        viewType: 'audit',
        showViewSelector: false,
        lastExpandedGroup: null,
        showingSpecificSection: false,
        showingMainMenu: true,
        showingRevision: false,
        showSettingsModal: false,
        showPrivacyNoticeModal: false,

        // ⚡ PERFORMANCE: Breadcrumb cache reduces initial RAM spike
        _cachedBannerTitle: null,
        _cachedBannerIcon: null,
        _bannerCacheDirty: true,

        // ⚡ PERFORMANCE: Progress title cache prevents string concatenation in reactive context
        _cachedProgressTitle: null,
        _progressTitleCacheDirty: true,
        updateAvailable: false,
        checkingForUpdates: false,
        updateCheckMessage: '',
        showBackupPrompt: false,
        searchVisible: false,
        searchQuery: '',
        searchResults: [],
        searchPagination: null,
        searchTimer: null,
        searchFilters: ['audit', 'notes', 'flashcards', 'mindmaps'],
        searchSortBy: 'relevance',
        searchSortDirection: 'asc',
        showAdvancedSearch: false,
        selectedSearchTags: [],
        selectedConfidenceRating: null,
        selectedConfidenceLevels: [],
        searchConfidenceDropdownOpen: false,
        searchSortDropdownOpen: false,
        isAuthenticated: false,
        showLoginScreen: true,
        user: null,
        authMethod: null,
        authToken: null,
        loginError: null,
        isLoading: false,
        isOnline: navigator.onLine,
        lastSyncTime: null,
        syncInProgress: false,
        currentRevisionSection: '',
        currentRevisionSectionTitle: '',
        currentRevisionTopics: [],
        currentRevisionResources: null,

        userNotes: {},
        showNoteEditor: false,
        noteEditorMode: 'create',
        noteEditorSectionId: null,
        noteEditorTitle: '',
        noteEditorContent: '',
        noteEditorId: null,
        noteEditorTags: [],
        editorSelectionUpdate: 0,
        noteEditorSelection: null,
        notesViewMode: 'card',
        notePreviewId: null,
        notesSort: 'updated',
        showEquationEditor: false,
        equationLatex: '',
        equationEditorMode: 'note',
        equationTargetShape: null,

        flashcardDecks: {},
        showFlashcardEditor: false,
        flashcardEditorMode: 'create',
        flashcardEditorSectionId: null,
        flashcardEditorDeckName: '',
        flashcardEditorDeckId: null,
        flashcardEditorCards: [],
        flashcardEditorCurrentCardFront: '',
        flashcardEditorCurrentCardBack: '',
        flashcardEditorTags: [],
        flashcardEditorCardsExpanded: false,
        flashcardEditorEditingCardIndex: null,
        showFlashcardTest: false,
        testFlashcards: [],
        currentTestCardIndex: 0,
        testCardFlipped: false,
        currentTestTitle: '',
        testAnswers: {},
        testCompleted: false,
        showTestResults: false,
        testReviewMode: null,
        testResultsHistory: [],

        showTestArea: false,
        showTestSetList: false,
        showTestSetBuilder: false,
        testSets: {},
        currentTestSetId: null,
        testSetBuilderName: '',
        testSetBuilderCards: [],
        testSetBuilderSearch: '',
        testSetBuilderExpandedDecks: {},
        testSetSort: 'updated',
        flashcardViewMode: 'card',
        flashcardCardSort: 'updated',
        showAdvancedSearch: false,
        advancedSearchTags: [],
        studyMaterialsFilter: 'all',
        contentFilterSection: null,
        contentFilterGroup: null,

        mindmaps: {},
        showMindmapEditor: false,
        mindmapEditorMode: 'create',
        mindmapEditorSectionId: null,
        mindmapEditorTitle: '',
        mindmapEditorId: null,
        mindmapEditorData: { nodes: [], connections: [], viewport: { x: 0, y: 0, scale: 1 } },
        mindmapEditorTags: [],
        mindmapsViewMode: 'card',
        mindmapsSort: 'updated',
        showMindmapNodeEditor: false,
        mindmapNodeEditorMode: 'create',
        mindmapNodeEditorContent: '',
        mindmapNodeEditorPosition: { x: 0, y: 0 },
        mindmapNodeEditorId: null,
        showingAnalytics: false,
        analyticsData: null,
        analyticsHistoryData: [],
        criticalTopicsPage: 0,
        strongTopicsPage: 0,
        recommendationsPage: 0,
        // ⚡ MEMORY FIX: chartInstances moved outside reactive state (see app.js) to prevent garbage collection issues

        // NOTE: Large read-only data (specificationData, groups, topicLookup) stored outside reactive state to save 300-400MB
        confidenceLevels: {},
        get confidenceScale() {
            return CONFIDENCE_SCALE;
        },

        showTagSelector: false,
        tagSelectorQuery: '',
        tagSelectorContext: null,
        tagSelectorExpandedSections: {},
        tagSelectorShowSelected: false,

        revisionAreaIndicatorStyle: 'outline',

        // ⚡ PERFORMANCE: Cached computed values to avoid recalculating on every render
        _cachedNotesGrouped: [],
        _cachedNotesGroupedDirty: true,
        _cachedFlashcardsGrouped: [],
        _cachedFlashcardsGroupedDirty: true,
        _cachedMindmapsGrouped: [],
        _cachedMindmapsGroupedDirty: true,
        _cachedInheritedTags: [],
        _cachedInheritedTagsDirty: true,
        _cachedFilteredDecksForBuilder: [],
        _cachedFilteredDecksForBuilderDirty: true,
        _cachedCriticalTopicsPage: [],
        _cachedCriticalTopicsPageDirty: true,
        _cachedStrongTopicsPage: [],
        _cachedStrongTopicsPageDirty: true,
        _cachedCurrentTags: [],
        _cachedCurrentTagsDirty: true,
        _cachedReviewCards: [],
        _cachedReviewCardsDirty: true,
        _cachedNotesForCurrentSection: [],
        _cachedNotesForCurrentSectionDirty: true,
        _cachedFlashcardDecksForCurrentSection: [],
        _cachedFlashcardDecksForCurrentSectionDirty: true,
        _cachedMindmapsForCurrentSection: [],
        _cachedMindmapsForCurrentSectionDirty: true,
        showCustomModal: false,
        modalType: 'alert',
        modalTitle: '',
        modalMessage: '',
        modalInputValue: '',
        modalCallback: null
    };
}
